#LogBack日志配置
logging:
  path: /home/serveradm/logs
  config: classpath:config/logback-spring.xml
  log-level: DEBUG

#改变fengin默认的 http 连接方式
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
 
#文件上传大小控制   
spring.http.multipart.maxFileSize: 50Mb
spring.http.multipart.maxRequestSize: 200Mb


#ureka服务提供方务过期时间配置
## 心跳间隔，5秒
eureka.instance.leaseRenewalIntervalInSeconds: 5
## 没有心跳的淘汰时间，10秒
eureka.instance.leaseExpirationDurationInSeconds: 10
# 定时刷新本地缓存时间
eureka.client.registryFetchIntervalSeconds: 5
# ribbon缓存时间
ribbon.ServerListRefreshInterval: 2000

#熔断配置
hystrix.threadpool.default.coreSize: 50
#无界限队列
hystrix.threadpool.default.maxQueueSize: -1
hystrix.command.default.circuitBreaker.requestVolumeThreshold: 100
hystrix.command.default.fallback.isolation.semaphore.maxConcurrentRequests: 50

#redis session 超时时间
spring.session.store-type: redis
server.session.timeout: 3600